---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Install latest version of "docker"
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
  - name: add Docker repo keys
    shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  - name: apt-key fingerprint
    shell: apt-key fingerprint 0EBFCD88
  - name: add repos
    shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  - name: apt update
    apt:
      update_cache: yes
  - name: apt install docker
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
